Rerender for newer GCC & Mamba
conda-forge/fftw-feedstock pull request #81
Opened 2021-12-01 18:03 UTC by ax3l

Trying to close #80 by rerendering the feedstock with latest compilers and mamba (default since [Oct](https://conda-forge.org/docs/user/announcements.html#announcements), fftw not rerendered since Sep).

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2021-12-01 18:03 UTC, ax3l commented
@conda-forge-admin, please rerender

2021-12-01 19:31 UTC, ax3l commented
@jakirkham let's see if this fixes it :) Ready for review & `automerge` label :)

2021-12-01 19:51 UTC, jakirkham approved these changes

2021-12-01 19:52 UTC, jakirkham commented
Thanks Axel! 😄

2021-12-02 10:20 UTC, duncanmmacleod commented
It would be good to include my changes from #82 here (if only to avoid another build).

2021-12-02 12:34 UTC, egpbos commented
Weird, I tried to rerender your PR @duncanmmacleod, since it says it was rerendered with conda-build 3.21.4, whereas this PR was rerendered with 3.21.6.

Does anyone understand why a newer rerender (the one in #82 was done 2 hours ago, the one in this PR was done 18 hours ago...) would use an older conda-build version?

2021-12-02 12:35 UTC, egpbos commented
@conda-forge-admin, please rerender

2021-12-02 12:36 UTC, duncanmmacleod commented
> Weird, I tried to rerender your PR @duncanmmacleod, since it says it was rerendered with conda-build 3.21.4, whereas this PR was rerendered with 3.21.6.
> 
> Does anyone understand why a newer rerender (the one in #82 was done 2 hours ago, the one in this PR was done 18 hours ago...) would use an older conda-build version?

I ran the rerender on my own machine, I must just have an older version of conda-build.

2021-12-02 12:44 UTC, egpbos commented
@ax3l could you allow @duncanmmacleod to cherry-pick and push his Python update commit to this branch?

2021-12-02 12:47 UTC, duncanmmacleod commented
> @ax3l could you allow @duncanmmacleod to cherry-pick and push his Python update commit to this branch?

alternatively, @ax3l could run

```bash
curl -Ls https://github.com/conda-forge/fftw-feedstock/pull/82/commits/3f461dafad8b3f3298a573c4226a1139eeb0f177.patch | git am -S
```

to pull my commit onto this branch; then regenerate the feedstock.

2021-12-02 17:10 UTC, ax3l commented
Patch from #82 applied, thanks!

2021-12-02 17:12 UTC, ax3l commented
@conda-forge-admin, please rerender

2021-12-02 18:50 UTC, egpbos approved these changes
Super, thanks!

2021-12-03 18:29 UTC, ax3l commented
Is it possible the `aarch64` builds are too slow currently, due to emulation? Looks like they ran 6 hrs on Azure.

2021-12-03 19:59 UTC, ax3l commented
@conda-forge-admin, please rerender

2021-12-03 20:38 UTC, beckermr requested changes
We should adjust the build script to run tests under qemu for the cross-compiled stuff on linux

2021-12-03 21:28 UTC, ax3l commented
Looks like tests are only available at build time already in this repo.

2021-12-03 21:37 UTC, beckermr commented
> Looks like tests are only available at build time already in this repo / in fftws logic, aren't they?

Yes. There are lines in the build.sh that turn them off for some platforms. We simply should remove those lines.

2021-12-03 22:30 UTC, beckermr commented
This bit too?

```
 # Disable Tests since we don't have enough time on Azure
  if [[ "$CI" == "azure" ]]; then
    TEST_CMD=""
  fi
```

2021-12-03 22:59 UTC, beckermr commented
The tests did not run. Trying this:

@conda-forge-admin rerender

2021-12-03 23:12 UTC, beckermr commented on recipe/build.sh
> +if [[ "${CONDA_BUILD_CROSS_COMPILATION:-}" == 1 && "${CROSSCOMPILING_EMULATOR:-}" == "" ]]; then
```suggestion
if [[ "${CONDA_BUILD_CROSS_COMPILATION:-}" == 1 && "${CROSSCOMPILING_EMULATOR:-}" != "" ]]; then
```

2021-12-03 23:47 UTC, beckermr commented
ahhhhh!

This build is installing an ancient ci-setup version?

```
conda-forge/linux-64::conda-forge-ci-setup-3.13.0-py38h7bc8238_0
```

2021-12-03 23:50 UTC, beckermr commented
I think it might be the boa run constraint? The boa version is 0.6.2.

2021-12-04 15:46 UTC, beckermr commented
@conda-forge-admin rerender

2021-12-04 15:53 UTC, beckermr commented on conda-forge.yml
>  idle_timeout_minutes: 90
```suggestion
# idle_timeout_minutes: 90
```

2021-12-04 15:54 UTC, beckermr commented
@conda-forge-admin rerender

2021-12-04 17:43 UTC, beckermr commented on recipe/build.sh
> +
```suggestion
```

2021-12-04 17:44 UTC, beckermr commented on recipe/build.sh
> +echo "============================================\n\n"
```suggestion
echo " "
echo "============================================"
echo "============================================"
echo "test command: ${TEST_CMD}"
echo "============================================"
echo "============================================"
echo " "
```

2021-12-04 17:47 UTC, beckermr approved these changes

2021-12-04 18:08 UTC, beckermr commented
@conda-forge-admin rerender

2021-12-04 20:26 UTC, merged

2021-12-04 20:27 UTC, beckermr commented
huzzah!

2021-12-05 03:57 UTC, ax3l commented
Thank you for your help! :)